import os
from datetime import datetime
from pathlib import Path

class HTMLReporter:
    """
    Generates an executive HTML report for Data Governance Audits.
    """
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.reports = []

    def add_result(self, dataset_name: str, report_data: dict):
        """Stores a validation result to be included in the report."""
        self.reports.append({
            "name": dataset_name,
            "data": report_data
        })

    def generate(self):
        """Builds and saves the HTML file."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        # HTML Header & CSS
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Data Governance Audit Report</title>
            <style>
                body {{ font-family: 'Segoe UI', sans-serif; margin: 40px; background-color: #f4f4f9; }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                .summary-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); margin-bottom: 20px; }}
                .pass {{ color: #27ae60; font-weight: bold; }}
                .fail {{ color: #c0392b; font-weight: bold; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
                th {{ background-color: #ecf0f1; text-align: left; padding: 10px; }}
                td {{ padding: 10px; border-bottom: 1px solid #ddd; }}
                .badge {{ padding: 5px 10px; border-radius: 4px; color: white; font-size: 0.8em; }}
                .bg-CRITICAL {{ background-color: #e74c3c; }}
                .bg-HIGH {{ background-color: #e67e22; }}
                .bg-MEDIUM {{ background-color: #f1c40f; color: #333; }}
            </style>
        </head>
        <body>
            <h1>Data Quality & Governance Report</h1>
            <p><strong>Execution Date:</strong> {timestamp}</p>
            <p><strong>Environment:</strong> Production (Simulated)</p>
        """

        # Loop through results
        for item in self.reports:
            r = item['data']
            status_class = "pass" if r['status'] == "PASSED" else "fail"
            
            html_content += f"""
            <div class="summary-card">
                <h2>Dataset: {item['name'].upper()}</h2>
                <p>Quality Score: <strong>{r['overall_score']}/100</strong> 
                   <span class="{status_class}">({r['status']})</span>
                </p>
            """
            
            if r['details']:
                html_content += """
                <table>
                    <thead>
                        <tr>
                            <th>Severity</th>
                            <th>Column</th>
                            <th>Rule Violation</th>
                            <th>Failed Rows</th>
                        </tr>
                    </thead>
                    <tbody>
                """
                for issue in r['details']:
                    html_content += f"""
                        <tr>
                            <td><span class="badge bg-{issue['severity']}">{issue['severity']}</span></td>
                            <td>{issue['column']}</td>
                            <td>{issue['rule']}</td>
                            <td>{issue['failed_rows']}</td>
                        </tr>
                    """
                html_content += "</tbody></table>"
            else:
                html_content += "<p>No issues detected. Clean dataset.</p>"
            
            html_content += "</div>"

        # Footer
        html_content += """
            <div style="text-align: center; color: #7f8c8d; margin-top: 40px;">
                <p>Generated by Enterprise Data Quality Framework v1.0</p>
            </div>
        </body>
        </html>
        """

        # Save File
        filename = f"DQ_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        full_path = self.output_dir / filename
        
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        return full_path
